[package]
name = "airdrop"
version = "0.1.0"
authors = ["utx0 <utx0@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.2.0", features = ["full"] }
reqwest = { version = "0.11.1", features = ["json"] }
serde = { version = "1.0.123", features = ["derive"] }


[[bin]]
name = "atom"
path = "src/atom/main.rs"

[[bin]]
name = "rune"
path = "src/rune/main.rs"